name: tamkeen
description: "Tamkeen - منصة المرأة العراقية للتمكين الاقتصادي"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1

  # =========================
  # State Management
  # =========================
  flutter_riverpod: ^3.3.2

  # =========================
  # Routing
  # =========================
  go_router: ^17.3.0

  # =========================
  # Backend
  # =========================
  supabase_flutter: ^2.6.0

  # =========================
  # Fonts
  # =========================
  google_fonts: ^8.1.0

  # =========================
  # SVG Images
  # =========================
  flutter_svg: ^2.2.0

  # =========================
  # Cached Images
  # =========================
  cached_network_image: ^3.4.1

  # =========================
  # Pick Images
  # =========================
  image_picker: ^1.2.0
  file_picker: ^10.3.2

  # =========================
  # Path
  # =========================
  path: ^1.9.1

  # =========================
  # Date Formatting
  # =========================
  intl: ^0.20.2

  # =========================
  # UUID
  # =========================
  uuid: ^4.5.1

  # =========================
  # Local Storage
  # =========================
  shared_preferences: ^2.5.3

  # =========================
  # Network Requests
  # =========================
  dio: ^5.9.0

  # =========================
  # Animations
  # =========================
  flutter_animate: ^4.5.2

  # =========================
  # Skeleton Loading
  # =========================
  shimmer: ^3.0.0

  # =========================
  # Icons
  # =========================
  hugeicons: ^1.1.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/lottie/